// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bjimpute
Rcpp::NumericVector bjimpute(SEXP y, SEXP cen, SEXP x, SEXP inibeta);
RcppExport SEXP _rotsf_bjimpute(SEXP ySEXP, SEXP cenSEXP, SEXP xSEXP, SEXP inibetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type cen(cenSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inibeta(inibetaSEXP);
    rcpp_result_gen = Rcpp::wrap(bjimpute(y, cen, x, inibeta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rotsf_bjimpute", (DL_FUNC) &_rotsf_bjimpute, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rotsf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
