# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bjimpute <- function(y, cen, x, inibeta) {
    .Call(`_rotsf_bjimpute`, y, cen, x, inibeta)
}

